DonanımPazar/Models/Adviewmodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DonanımPazar.Models
{
    public class Adviewmodel
    {

        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public string pro_des { get; set; }
        public Nullable<int> pro_price { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string u_name { get; set; }
        public string u_image { get; set; }
        public string u_contact { get; set; }

    }
}

DonanımPazar/Controllers/AdminController.cs
using DonanımPazar.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using System.Web.UI;


namespace DonanımPazar.Controllers
{
    public class AdminController : Controller
    {
        DonanımPazarEntities db = new DonanımPazarEntities();

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(tbl_admin avm)
        {
            tbl_admin ad = db.tbl_admin.Where(x => x.ad_username == avm.ad_username && x.ad_password == avm.ad_password).SingleOrDefault();
            if (ad != null)
            {
                Session["ad_id"] = ad.ad_id.ToString();
                return RedirectToAction("ViewCategory");
            }
            else
            {
                ViewBag.error = "Geçersiz Kullanıcı Adı veya Şifre";
            }

            return View();
        }

        public ActionResult Create()
        {
            if (Session["ad_id"]==null)
            {
                return RedirectToAction("login");

            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(tbl_category cvm, HttpPostedFileBase imgfile)
        {
            string path = uploadimgfile(imgfile);
            if (path.Equals("-1"))
            {
                ViewBag.error = "Resim Yüklenemedi....";
            }
            else
            {
                tbl_category cat = new tbl_category();
                cat.cat_name = cvm.cat_name;
                cat.cat_image = path;
                cat.cat_status = 1;
                cat.cat_fk_ad = Convert.ToInt32(Session["ad_id"].ToString());
                db.tbl_category.Add(cat);
                db.SaveChanges();
                return RedirectToAction("ViewCategory");
            }

            return View();
        }

        public ActionResult ViewCategory(int?page)
        {
            int pagesize = 9, pageindex = 1;
            pageindex = page.HasValue ? Convert.ToInt32(page) : 1;
            var list = db.tbl_category.Where(x => x.cat_status == 1).OrderByDescending(x => x.cat_id).ToList();
            IPagedList<tbl_category> stu = list.ToPagedList(pageindex, pagesize);


            return View(stu);
            
        }

        public ActionResult ManageAds(int? page)
        {
            if (Session["ad_id"] == null)
            {

                return RedirectToAction("Login");
            }

            int pageSize = 10;
            int pageIndex = page ?? 1;

            
            var ads = db.tbl_product.OrderBy(x => x.pro_id).ToPagedList(pageIndex, pageSize);

            return View(ads);
        }


        [HttpPost]
        public ActionResult DeleteAd(int id)
        {
            if (Session["ad_id"] == null)
            {
                return RedirectToAction("Login");
            }

            var ad = db.tbl_category.FirstOrDefault(x => x.cat_id == id);

            if (ad != null)
            {
                db.tbl_category.Remove(ad);
                db.SaveChanges();
                return RedirectToAction("ManageAds");
            }
            else
            {
                ViewBag.Error = "Ilan bulunamadı";
                return View("ManageAds");
            }
        }

        public ActionResult ManageUsers()
        {
            if (Session["ad_id"] == null)
            {
                return RedirectToAction("Login");
            }

            var users = db.tbl_user.ToList();
            return View(users);
        }

        [HttpPost]
        public ActionResult DeleteUser(int id)
        {
            if (Session["ad_id"] == null)
            {
                return RedirectToAction("Login");
            }

            var user = db.tbl_user.FirstOrDefault(x => x.u_id == id);

            if (user != null)
            {
                db.tbl_user.Remove(user);
                db.SaveChanges();
                return RedirectToAction("ManageUsers");
            }
            else
            {
                ViewBag.Error = "Kullanıcı bulunamadı";
                return View("ManageUsers");
            }
        }



        public string uploadimgfile(HttpPostedFileBase file)
            {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {

                        path = Path.Combine(Server.MapPath("/Content/upload"), random + Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        path = "/Content/upload/" + random + Path.GetFileName(file.FileName);

                           // ViewBag.Message = "Dosya Ekleme Başarılı";
                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('Sadece jpg ,jpeg or png formatlar geçerlidir....'); </script>");
                }
            }

            else
            {
                Response.Write("<script>alert('Lütfen Dosya Seçin'); </script>");
                path = "-1";
            }



            return path;
        }



    }
}

DonanımPazar/Controllers/UserController.cs
using DonanımPazar.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace DonanımPazar.Controllers
{
    public class UserController : Controller
    {
        DonanımPazarEntities db = new DonanımPazarEntities();
        // GET: User
        public ActionResult Index(int? page)
        {
            int pagesize = 9, pageindex = 1;
            pageindex = page.HasValue ? Convert.ToInt32(page) : 1;
            var list = db.tbl_category.Where(x => x.cat_status == 1).OrderByDescending(x => x.cat_id).ToList();
            IPagedList<tbl_category> stu = list.ToPagedList(pageindex, pagesize);


            return View(stu);
        }
        


        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(tbl_user uvm, HttpPostedFileBase imgfile)
        {
            string path = uploadimgfile(imgfile);
            if (path.Equals("-1"))
            {
                ViewBag.error = "Resim Yüklenemedi....";
            }
            else
            {
                tbl_user u = new tbl_user();
                u.u_name = uvm.u_name;
                u.u_email = uvm.u_email;
                u.u_password = uvm.u_password;
                u.u_image = path;
                u.u_contact = uvm.u_contact;
                db.tbl_user.Add(u);
                db.SaveChanges();
                return RedirectToAction("Login");

            }

            return View();
        }

        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult login(tbl_user avm)
        {
            tbl_user ad = db.tbl_user.Where(x => x.u_email == avm.u_email && x.u_password == avm.u_password).SingleOrDefault();
            if (ad != null)
            {

                Session["u_id"] = ad.u_id.ToString();
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.error = "Hatalı Kullanıcı Adı yada Şifre";

            }

            return View();
        }

        [HttpGet]
        public ActionResult CreateAd()
        {
            List<tbl_category> li = db.tbl_category.ToList();
            ViewBag.categorylist = new SelectList(li, "cat_id", "cat_name");

            return View();
        }

        [HttpPost]
        public ActionResult CreateAd(tbl_product pvm, HttpPostedFileBase imgfile)
        {
            List<tbl_category> li = db.tbl_category.ToList();
            ViewBag.categorylist = new SelectList(li, "cat_id", "cat_name");


            string path = uploadimgfile(imgfile);
            if (path.Equals("-1"))
            {
                ViewBag.error = "Resim Yüklenemedi....";
            }
            else
            {
                tbl_product p = new tbl_product();
                p.pro_name = pvm.pro_name;
                p.pro_price = pvm.pro_price;
                p.pro_image = path;
                p.pro_fk_cat = pvm.pro_fk_cat;
                p.pro_des = pvm.pro_des;
                p.pro_fk_user = Convert.ToInt32(Session["u_id"].ToString());
                db.tbl_product.Add(p);
                db.SaveChanges();
                Response.Redirect("index");

            }

            return View();
        }


        public ActionResult Ads(int? id, int? page)
        {
            int pagesize = 6, pageindex = 1;
            pageindex = page.HasValue ? Convert.ToInt32(page) : 1;
            var list = db.tbl_product.Where(x => x.pro_fk_cat == id).OrderByDescending(x => x.pro_id).ToList();
            IPagedList<tbl_product> stu = list.ToPagedList(pageindex, pagesize);


            return View(stu);


        }

        [HttpPost]
        public ActionResult Ads(int? id, int? page, string search)
        {
            int pagesize = 6, pageindex = 1;
            pageindex = page.HasValue ? Convert.ToInt32(page) : 1;
            var list = db.tbl_product.Where(x => x.pro_name.Contains(search)).OrderByDescending(x => x.pro_id).ToList();
            IPagedList<tbl_product> stu = list.ToPagedList(pageindex, pagesize);


            return View(stu);


        }


        public ActionResult ViewAd(int? id)
        {
            Adviewmodel ad = new Adviewmodel();
            tbl_product p = db.tbl_product.Where(x => x.pro_id == id).SingleOrDefault();
            ad.pro_id = p.pro_id;
            ad.pro_name = p.pro_name;
            ad.pro_image = p.pro_image;
            ad.pro_price = p.pro_price;
            ad.pro_des = p.pro_des;
            tbl_category cat = db.tbl_category.Where(x => x.cat_id == p.pro_fk_cat).SingleOrDefault();
            ad.cat_name = cat.cat_name;
            tbl_user u = db.tbl_user.Where(x => x.u_id == p.pro_fk_user).SingleOrDefault();
            ad.u_name = u.u_name;
            ad.u_image = u.u_image;
            ad.u_contact = u.u_contact;
            ad.pro_fk_user = u.u_id;




            return View(ad);
        }


        public ActionResult Signout()
        {
            Session.RemoveAll();
            Session.Abandon();

            return RedirectToAction("Index");
        }



        public ActionResult DeleteAd(int? id)
        {

            tbl_product p = db.tbl_product.Where(x => x.pro_id == id).SingleOrDefault();
            db.tbl_product.Remove(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public string uploadimgfile(HttpPostedFileBase file)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {

                        path = Path.Combine(Server.MapPath("/Content/upload"), random + Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        path = "/Content/upload/" + random + Path.GetFileName(file.FileName);

                        // ViewBag.Message = "Dosya Ekleme Başarılı";
                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('Sadece jpg ,jpeg or png formatlar geçerlidir....'); </script>");
                }
            }

            else
            {
                Response.Write("<script>alert('Lütfen Dosya Seçin'); </script>");
                path = "-1";
            }



            return path;
        }

        




    }







}

DonanımPazar/Views/User/Ads.cshtml
@using PagedList.Mvc
@model  PagedList.IPagedList<DonanımPazar.Models.tbl_product>

@{
    ViewBag.Title = "Ads";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View  Category</title>
    <link href="~/Content/paginition.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <style>
        body {
            background-color: #e9f0f7;
        }

        .rounded-box {
            border-radius: 10px;
            overflow: hidden;
        }
    </style>


</head>

<body>





    <div class="row" style="margin-bottom:40px">

        

        <div class="col-lg-8 col-md-8">

            @using (@Html.BeginForm("Ads", "User"))
            {
                <div class="navbar-form ">
                    <div class="form-group">

                        <input type="text" class="form-control" placeholder="Search" name="search" id="search">
                    </div>
                    <button type="submit" class="btn btn-success">Search</button>
                </div>
            }



            <div class="row">
                @{int x = 0;}
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        x++;
                        <div class="col-lg-4 col-md-4" style="height:200px;margin-top:100px">

                            <img class="img img-responsive cimg" src="@Url.Content(item.pro_image)" style=" height:100%;width:100% ;border-radius:50px 50px 50px 50px" />
                            <h4 style="color:#808080; font-family:'Arial Rounded MT';text-align:center"> @Html.ActionLink(@item.pro_name, "ViewAd", new { id = @item.pro_id })</h4>

                        </div>

                    }
                }

                
            </div>
        </div>


       





    </div>


    

    <div id="container" style="margin-left: 20px">
        <p></p>
        <p></p>
        <div class="pagination" style="margin-left: 400px">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Ads", new { page }))
        </div>
    </div>
</body>
</html>

DonanımPazar/Views/User/CreateAd.cshtml
@model DonanımPazar.Models.tbl_product
@{

}

<style>
    #box {
        border: 1px solid black;
        height: 100%;
    }

    #main-div {
        height: 900px;
        
        background-size: 100% 900px;
    }

    .insidebox {
        border: 1px solid black;
        margin: 10% auto 10% auto;
        max-width: 500px;
        min-width: 200px;
        padding-left: 60px;
        padding-right: 60px;
        border-radius: 10px;
        background-color: whitesmoke;
    }

    div h1 {
        text-align: center;
    }

    p#para {
        text-align: center;
        font-size: 14px;
    }
</style>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />




<script src="js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery.js"></script>
<div id="main-div">
    <div id="box" class="img-responsive">
        @using (Html.BeginForm("CreateAd",
                        "User",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
        {
            <div class="insidebox">
                <div> <h1>Ürün Ekleyin</h1></div>



                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @Html.DropDownListFor(x => x.pro_fk_cat, ViewBag.categorylist as SelectList, "--Kategori Seçiniz--", new { @class = "form-control" })
                    </div>
                    <span style="color:red">   @Html.ValidationMessageFor(x => x.pro_fk_cat) </span>

                </div>



                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.TextBoxFor(x => x.pro_name, new { @class = "form-control", @placeholder = "Ürün adı" })

                    </div>
                    <span style="color:red">   @Html.ValidationMessageFor(x => x.pro_name) </span>

                </div>



                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.TextBoxFor(x => x.pro_price, new { @class = "form-control", @placeholder = "Fiyat" })

                    </div>
                    <span style="color:red">   @Html.ValidationMessageFor(x => x.pro_price) </span>

                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.TextBoxFor(x => x.pro_des, new { @class = "form-control", @placeholder = "Açıklama" })

                    </div>
                    <span style="color:red">   @Html.ValidationMessageFor(x => x.pro_des) </span>

                </div>


                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>

                        <input type="file" name="imgfile" id="imgfile" class="form-control" required="required" />



                    </div>


                </div>



                <div class="form-group">

                    <input type="submit" value="Ekle" class="btn btn-success btn-block" />

                </div>

                <div class="form-group">
                    <p style="color:red">@ViewBag.error</p>
                </div>



            </div>

        }
    </div>

</div>


<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DonanımPazar/Views/User/Index.cshtml
@using PagedList.Mvc
@model  PagedList.IPagedList<DonanımPazar.Models.tbl_category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View  Category</title>
    <link href="~/Content/paginition.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <style>
        body {
            background-color: #e9f0f7;
        }

        .rounded-box {
            border-radius: 10px;
            overflow: hidden;
        }
    </style>


</head>

<body>


    <div class="container" style="height:1150px; ">
        <div class="row">
            <div class="col-lg-12" style="height:100px; border:1px solid solid; ">



            </div>

        </div>



        <div class="row" style="margin-bottom:40px">
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-4" style="height: 200px; margin-top: 100px; box-shadow: 20px 20px 60px #c6ccd2, -20px -20px 60px #ffffff;">
                        <img src="@Url.Content(item.cat_image)" style="height:100%;width:100%;border-radius:50px 50px 50px 50px" />
                        <h4 style="color:#808080; font-family:'Arial Rounded MT';text-align:center">@Html.ActionLink(@item.cat_name, "Ads", new { id = @item.cat_id })</h4>

                    </div>
                }
            }




        </div>
    </div>

        <div id="container" style="margin-left: 20px">
            <p></p>
            <p></p>
            <div class="pagination" style="margin-left: 400px">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
</body>
</html>

DonanımPazar/Views/User/Register.cshtml
@model DonanımPazar.Models.tbl_user
@{
    Layout = null;
}

<style>



    #box {
        border: 1px solid black;
        height: 100%;
        border-radius: 10px;
        background: #d3e6f8;
    }


    .insidebox {
        border: 1px solid black;
        margin: 10% auto 10% auto;
        max-width: 500px;
        min-width: 200px;
        padding-left: 60px;
        padding-right: 60px;
        border-radius: 50px;
        background-color: whitesmoke;
        box-shadow: 20px 20px 60px #8eb3d5, -20px -20px 60px #c0f2ff;
        background: #a7d2fb;
    }

    div h1 {
        text-align: center;
    }

    p#para {
        text-align: center;
        font-size: 14px;
    }
</style>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />


<script src="js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery.js"></script>
<div id="main-div">
    <div id="box" class="img-responsive">
        @using (Html.BeginForm("Register",
                  "User",
                  FormMethod.Post,
                  new { enctype = "multipart/form-data" }))
        {
            <div class="insidebox">
                <div> <h1>Kayıt Ol</h1></div>




                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.TextBoxFor(x => x.u_name, new { @class = "form-control", @placeholder = "Kullanici Adi" })

                    </div>
                    <span style="color:red"> @Html.ValidationMessageFor(x => x.u_name)  </span>

                </div>


                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.TextBoxFor(x => x.u_email, new { @class = "form-control", @placeholder = "Email" })

                    </div>
                    <span style="color:red"> @Html.ValidationMessageFor(x => x.u_email)  </span>

                </div>


                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                        @Html.PasswordFor(x => x.u_password, new { @class = "form-control", @placeholder = "Şifre" })

                    </div>
                    <span style="color:red"> @Html.ValidationMessageFor(x => x.u_password)  </span>



                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                            @*<asp:TextBox ID="TextBox1" runat="server" class="form-control" placeholder="Username" required="required"></asp:TextBox>*@
                            @Html.TextBoxFor(x => x.u_contact, new { @class = "form-control", @placeholder = "Telefon Numarası" })

                        </div>
                        <span style="color:red"> @Html.ValidationMessageFor(x => x.u_contact)  </span>

                    </div>

                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>

                        <input type="file" name="imgfile" id="imgfile" class="form-control" required="required" />

                    </div>


                </div>



                <div class="form-group">

                    <input type="submit" value="Kaydet" class="btn btn-success btn-block" />

                </div>

                <div class="form-group">
                    <p style="color:red">@ViewBag.error</p>
                </div>



            </div>

        }
    </div>

</div>


<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DonanımPazar/Views/User/ViewAd.cshtml
@model DonanımPazar.Models.Adviewmodel
@{
    ViewBag.Title = "ViewAd";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>
    td {
        padding: 20px;
    }
    
    .center-image {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    
</style>



<div class="row">
    

    <div class="col-lg-8 col-md-8">

        <div>
            <h1>@Model.pro_name <small>AD-ID:@Model.pro_id</small></h1>
        </div>

        <img src="@Url.Content(@Model.pro_image)" style="width:800PX; height:450PX" />

        <div>
            <h1> </h1>
            <p>@Model.pro_des</p>
        </div>

        <table>

            <tr> <td>Fiyat : </td> <td>@Model.pro_price </td> </tr>
            <tr> <td>Kategori  : </td> <td>@Model.cat_name </td> </tr>
            <tr> <td>İlan Sahibi   : </td> <td>@Model.u_name <img src="@Url.Content(@Model.u_image)" style="width:40px; height:40px" /> </td> </tr>
            <tr> <td>İletişim  : </td> <td>@Model.u_contact  </td> </tr>
            <tr>
                <td colspan="2">
                    @if (Convert.ToInt32(Session["u_id"]) == Convert.ToInt32(Model.pro_fk_user))
                    {

                        @Html.ActionLink("Ürünü Kaldır", "DeleteAd", new { @class = "btn btn-info", id = Model.pro_id })



                    }
                </td>
            </tr>

        </table>



    </div>

    
</div>

DonanımPazar/Views/User/login.cshtml
@model DonanımPazar.Models.tbl_user
@{
    ViewBag.Title = "login";
    Layout = "/Views/Shared/_Layout1.cshtml";
}

<style>
    #box {
        border: 1px solid black;
        height: 100%;
        border-radius: 10px;
        background: #e9f0f7;
    }

    .insidebox {
        border: 1px solid black;
        margin: 10% auto 10% auto;
        max-width: 500px;
        min-width: 200px;
        padding-left: 60px;
        padding-right: 60px;
        border-radius: 50px;
        background-color: whitesmoke;
        box-shadow: 20px 20px 60px #8eb3d5, -20px -20px 60px #c0f2ff;
        background: #a7d2fb;
    }

    div h1 {
        text-align: center;
    }

    p#para {
        text-align: center;
        font-size: 14px;
    }
</style>

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />


<script src="js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery.js"></script>
<div id="main-div">
    <div id="box" class="img-responsive">
        @using (Html.BeginForm())
        {
            <div class="insidebox">
                <div> <h1>Giriş Yap</h1></div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                        @Html.TextBoxFor(x => x.u_email, new { @class = "form-control", @placeholder = "Email" })
                    </div>
                    <span style="color:red"> @Html.ValidationMessageFor(x => x.u_email) </span>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                        @Html.PasswordFor(x => x.u_password, new { @class = "form-control", @placeholder = "Sifre" })
                    </div>
                    <span style="color:red"> @Html.ValidationMessageFor(x => x.u_password) </span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-success btn-block" />
                </div>

                <div class="form-group">
                    <p style="color:red">@ViewBag.error</p>
                </div>

                <!-- Kayıt olma için link -->
                <div class="form-group">
                    <p>Hesabınız Yok Mu? <a href="@Url.Action("Register", "User")">Kayıt Ol</a></p>
                    <p>Admin Misiniz? <a href="@Url.Action("Login", "Admin")">Giriş Yap</a></p>
                </div>
            </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}